default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: instagram1
  host: localhost
  username: postgres
  password: prasanna

test:
  <<: *default
  database: instagram_test
  host: localhost
  username: postgres
  password: prasanna

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
